
networks:
  openproject_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: openproject_db
      POSTGRES_USER: openproject_user
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    networks:
      - openproject_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memcached:
    image: memcached:latest
    container_name: memcached_container
    restart: always
    ports:
      - "11211:11211"
    networks:
      - openproject_network

  openproject:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: "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"
    container_name: openproject_app
    restart: always
    environment:
      SECRET_KEY_BASE: "cf99476b3e3d8c9f1843d20b4cd7f1dc4a5c19c777277bc832c8cb39ce129449bc76f3736dc7d27bb1efdb78e68137663d47ac1e82bb251cddd599777a238505"
      RAILS_ENV: "production"
      MEMCACHE_SERVERS: "memcached:11211"
      OPENPROJECT_HTTPS: "false"
      MIGRATE_DB: "yes"       
      PRECOMPILE_ASSETS: "yes" 
    depends_on:
      - postgres
      - memcached
    ports:
      - "3001:3000"
    networks:
      - openproject_network
    volumes:
      - ./config/database.yml:/app/config/database.yml
  
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: apache_container
    restart: always
    ports:
      - "80:80"
    networks:
      - openproject_network
    depends_on:
      - openproject

volumes:
  postgres_data:
